In [192]:
num=int(input("enter a integer"))
print(type(num))

In [193]:
num=int(input("enter a integer"))
print(type(num))

In [194]:
for i in range(1,11):
  print(f'{num}x{i}={num*i}')

5x1=5
5x2=10
5x3=15
5x4=20
5x5=25
5x6=30
5x7=35
5x8=40
5x9=45
5x10=50


In [195]:
a=float(input("enternfirst num"))
b=float(input("enter sec num"))
print(f'addition: {a+b}')
print(f'subtraction: {a-b}')
print(f'mul:{a*b}')
print(f'div:{a/b}')

addition: 11.0
subtraction: -1.0
mul:30.0
div:0.8333333333333334


In [196]:
numbers=[1,2,3,5,7,14]
tot=0
for i in numbers:
  tot+=i
avg=tot/len(numbers)
print(tot)
print(avg)

32
5.333333333333333


In [197]:
import numpy as np


In [198]:
marks=np.array([75,65,88,99,23.65,True]) #false will not defined here error will come
print("array:", marks)
print("type:",type(marks))

array: [75.   65.   88.   99.   23.65  1.  ]
type: <class 'numpy.ndarray'>


In [199]:
a0d=np.array(40)
print(f'array:{a0d}')
print(f'type:{type(a0d)}')
print(f'shape:{a0d.shape}')
print(f'size:{a0d.size}')
print(f'dimension:{a0d.ndim}')

array:40
type:<class 'numpy.ndarray'>
shape:()
size:1
dimension:0


In [200]:
a2d=np.array([[1,2,3],[4,5,6]])
print(f'Array:{a2d}')
print(f'shape:{a2d.shape}')
print(f'size:{a2d.size}')
print(f'dimension:{a2d.ndim}')

Array:[[1 2 3]
 [4 5 6]]
shape:(2, 3)
size:6
dimension:2


In [201]:
a3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,34,56],[0,0,0],[1,44,77]],[[22,44,56],[35,77,88],[54,77,88]]])
print(f'Array:{a3d}')
print(f'shape:{a3d.shape}')
print(f'size:{a3d.size}')
print(f'dimension:{a3d.ndim}')


Array:[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1 34 56]
  [ 0  0  0]
  [ 1 44 77]]

 [[22 44 56]
  [35 77 88]
  [54 77 88]]]
shape:(3, 3, 3)
size:27
dimension:3


In [202]:
print(f'row1, column 1;{a2d[0,0]}')
print(f'row12, column 1;{a2d[1,0]}')

row1, column 1;1
row12, column 1;4


In [203]:
print(f'Second row :{a2d[1]}')
print(f'third column :{a2d[:,2]}')


Second row :[4 5 6]
third column :[3 6]


In [204]:
print(a3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1 34 56]
  [ 0  0  0]
  [ 1 44 77]]

 [[22 44 56]
  [35 77 88]
  [54 77 88]]]


In [214]:
print(a3d)
print(a3d[0,1,2])
print(a3d[1])
print(a3d[1,:,:])
print(a3d[0,:,:])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1 34 56]
  [ 0  0  0]
  [ 1 44 77]]

 [[22 44 56]
  [35 77 88]
  [54 77 88]]]
6
[[ 1 34 56]
 [ 0  0  0]
 [ 1 44 77]]
[[ 1 34 56]
 [ 0  0  0]
 [ 1 44 77]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [206]:
print(a3d[:,0,0])

[ 1  1 22]


In [207]:
marks1=np.array([12,44,66,68,34,67,234])
print(f'First four:{marks1[:4]}')
print(f'last four :{marks1[-4:]}')
print(f'alternate:{marks1[::2]}')
print(f'reverse:{marks1[::-1]}')
print(f'middle:{marks1[3:6]}')

First four:[12 44 66 68]
last four :[ 68  34  67 234]
alternate:[ 12  66  34 234]
reverse:[234  67  34  68  66  44  12]
middle:[68 34 67]


In [208]:
marks1[:6]=marks1[5::-1] #[end position:start pos:step]  here 1st storing in reverse then printing
print(marks1)

[ 67  34  68  66  44  12 234]


In [209]:
print(f'reverse first six:{marks1[5::-1]}')
print(f'reverse last six:{marks1[-6]}')

reverse first six:[12 44 66 68 34 67]
reverse last six:34


In [210]:
zeros=np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [211]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [212]:
full=np.full((2,3),7)
full

array([[7, 7, 7],
       [7, 7, 7]])

In [213]:
arr=np.ones(5,dtype=int)
arr

array([1, 1, 1, 1, 1])

arrange() and linspace()

In [217]:
a=np.arange(0,10,2)
print(f'arange:{a}')
b=np.linspace(0,10,5)
print(f'linspace:{b}')

arange:[0 2 4 6 8]
linspace:[ 0.   2.5  5.   7.5 10. ]


In [218]:
# generate 1 to 20 with using a arange
p=np.arange(1,20,5)
print(f'arange:{p}')

arange:[ 1  6 11 16]


In [219]:
# generate 0 to 1 with 11 points using linspace
q=np.linspace(0,1,11)
print(f'linspace:{q}')


linspace:[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [220]:
print(f'random decimal:{np.random.rand(5)}')
#print(f'random integer:{np.random.randint(1,100,

random decimal:[0.6969119  0.2588314  0.66559553 0.9203053  0.7688559 ]


In [221]:
np.random.seed(42)
print(f'random decimsal:{np.random.random(5)}')

random decimsal:[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [222]:
print(f'random Integer:{np.random.randint(1,11,size=5)}')

random Integer:[3 7 8 5 4]


In [223]:
print(a2d)
print(a2d[1,0:2])

[[1 2 3]
 [4 5 6]]
[4 5]


In [226]:
print(a2d[0:2,1])
print(a2d[0:1,1])

[2 5]
[2]


In [227]:
print(a2d[0:2,0:2])

[[1 2]
 [4 5]]
